# Increases the amount of memory Gradle can use and optimizes the GC
	# -XX:+UseZGC
	org.gradle.jvmargs=-Xmx4G
# Helps with build times
	org.gradle.parallel=true
# Caches Dependencies for faster build times.
	org.gradle.caching=true

# Fabric Properties
	# Get new versions at https://fabricmc.net/develop and https://lambdaurora.dev/tools/import_quilt.html
	minecraft_version=26.3-snapshot-4
	loader_version=0.19.3
	min_loader_version=0.19.0

# Mod Properties
    mod_id = glowtone
	mod_version = 1.0.2
	maven_group = net.frozenblock
	archives_base_name = Glowtone

# Dependencies
	fabric_api_version=0.155.1+26.3

# Optimization
    sodium_version=mc26.2-0.9.0-fabric
    run_sodium=false
